apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dockerio
  namespace: user-pipelines
spec:
  backendType: akeyless
  data:
    - key: dockerhub
      name: .dockerconfigjson
  template:
    type: kubernetes.io/dockerconfigjson
