apiVersion: v1
kind: Namespace
metadata:
  name: tekton-chains
spec:
  finalizers:
  - kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-argocd
  namespace: tekton-chains
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
## Role for creating externalsecrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secret-creation
  namespace: tekton-chains
rules:
- apiGroups: ["kubernetes-client.io"]
  resources: ["externalsecrets"]
  verbs: ["create","list", "get", "patch", "delete"]
---
## Rolebinding to create externalsecrets
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grant-argocd-external-secrets
  namespace: tekton-chains
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secret-creation
---
