apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-argocd
  namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret-cp
  namespace: openshift-config
spec:
  backendType: akeyless
  data:
    - key: clientSecret
      name: clientSecret
  template:
    type: Opaque
