apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-client-secret-cp
  namespace: openshift-config
spec:
  backendType: akeyless
  data:
    - key: clientSecret
      name: clientSecret
  template:
    type: Opaque
