apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: signing-secrets
  namespace: tekton-chains
spec:
  backendType: akeyless
  data:
    - key: cosign.pub
      name: cosign.pub
    - key: cosign.key
      name: cosign.key
    - key: password
      name: password
  template:
    type: Opaque
